### ISSUE TITLE
Ship placement by default

### ISSUE THREAD

**Issue by mi11y** [cs361w2019-osu/sprint1-project-group-13#17]
- [x] New map automatically selects new ship to place
- [x] Implement pressing 'R' rotates ship to vertical position
- [x] Add a legend

**Comment by starburn** [comment]
![image](https://user-images.githubusercontent.com/8324981/52460533-a5f83b00-2b1f-11e9-9682-1e3745c41a6d.png)

**Comment by astra137** [comment]
Error thrown when hovering ship placement over edge, fixing now.

**Comment by astra137** [comment]
Guide and hover effects in place.
