### ISSUE TITLE
Captain's Quarters can be attacked twice

### ISSUE THREAD

**Issue by astra137** [cs361w2019-osu/sprint1-project-group-13#27]
In Board.java, `attack` should allow two hits to the same square if it's a ship's captain's quarters.

**Comment by starburn** [comment]
This won't be user testable until duplicate attacks on the same square are allowed, but it can still be implemented at any time.

**Comment by starburn** [comment]
I think the tests would be BoardTest.java.

**Comment by MiloChase** [comment]
Captains Quarters can be attacked the appropriate amount of times, but it has now broken the other non CQ tiles such that they can be attacked infinitely.
