### ISSUE TITLE
Sonar Pulse: Server Side

### ISSUE THREAD

**Issue by astra137** [cs361w2019-osu/sprint1-project-group-13#29]
Allow and add sonar pulse to list of sonars in Board.java if:
- at least one ship is sunk
- less than two sonars have been used
- sonar does not overlap with another sonar

I made private method `isSunk` to help (does not contain captains quarters logic yet).

**Comment by mi11y** [comment]
Please see #33 in regards to fixing the tests

**Comment by mi11y** [comment]
The tests specific for this issue should be passing.
