### ISSUE TITLE
Fix existing tests

### ISSUE THREAD

**Issue by astra137** [cs361w2019-osu/sprint1-project-group-13#33]
The coordinates of existing tests are backwards and that's why master branch is failing.

**Comment by mi11y** [comment]
Please note, the remaining test files still needed fixing

**Comment by mi11y** [comment]
Spoke with Rob, converting this issue to instead fix all tests in master.

**Comment by mi11y** [comment]
Forgot to mention this issue; the below commit fixes the remaining tests.

a64266882604eeda3ae0414a5843579117138b32
