### ISSUE TITLE
Create space laser

### ISSUE THREAD

**Issue by astra137** [cs361w2019-osu/sprint1-project-group-13#45]
- [x] Create new attacks list for laser attacks on Board
- [x] After a board has ≥ 1 sunk ships, attacks add to laser list instead of original attacks list
- [x] Change isSunk to ignore missile attacks if ship is submerged
- [x] Create Board test for sinking a ship then sinking submerged submarine
- [x] Create Board test for attacking a submerged submarine first does not sink it

**Comment by mi11y** [comment]
Ill claim this one, and Ill log here what I complete and what I have questions on.

**Comment by mi11y** [comment]
This work will be done on this [branch](https://github.com/cs361w2019-osu/sprint1-project-group-13/tree/issue-%2345)
